// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxTtS7-JR3-mLWg497wekZi6rLvfAY7M',
    appId: '1:585124389027:web:e75782f90e42e49a8d9f16',
    messagingSenderId: '585124389027',
    projectId: 'recipeappnew',
    authDomain: 'recipeappnew.firebaseapp.com',
    storageBucket: 'recipeappnew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXBVINMHUECrbXFwdz7Z1J0MyraWEbKtc',
    appId: '1:585124389027:android:e91a2e7c4a0d61cf8d9f16',
    messagingSenderId: '585124389027',
    projectId: 'recipeappnew',
    storageBucket: 'recipeappnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QGaJqGd6fN4Afik0NH0-VtyhjOLZgko',
    appId: '1:585124389027:ios:12a991d68a7ebab08d9f16',
    messagingSenderId: '585124389027',
    projectId: 'recipeappnew',
    storageBucket: 'recipeappnew.appspot.com',
    iosBundleId: 'com.example.recipeApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QGaJqGd6fN4Afik0NH0-VtyhjOLZgko',
    appId: '1:585124389027:ios:b4c238bf9882afbe8d9f16',
    messagingSenderId: '585124389027',
    projectId: 'recipeappnew',
    storageBucket: 'recipeappnew.appspot.com',
    iosBundleId: 'com.example.recipeApp1.RunnerTests',
  );
}
